__all__ = ["ui_fmrdlogin",
"ui_matchentry",
"ui_competitionentry",
"ui_teamentry",
"ui_venueentry",
"ui_venuehistoryentry", 
"ui_playerentry",
"ui_playerhistoryentry", 
"ui_managerentry",
"ui_refereeentry",
"ui_enviroentry",
"ui_lineupentry",
"ui_goalentry",
"ui_penaltyentry",
"ui_offenseentry",
"ui_subsentry",
"ui_switchentry"]
