# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/goal_entry.ui'
#
# Created: Sat Dec 17 17:42:20 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_GoalEntryDlg(object):
    def setupUi(self, GoalEntryDlg):
        GoalEntryDlg.setObjectName("GoalEntryDlg")
        GoalEntryDlg.resize(920, 460)
        GoalEntryDlg.setMinimumSize(QtCore.QSize(920, 460))
        GoalEntryDlg.setMaximumSize(QtCore.QSize(920, 460))
        self.line = QtGui.QFrame(GoalEntryDlg)
        self.line.setGeometry(QtCore.QRect(0, 50, 921, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(GoalEntryDlg)
        self.line_2.setGeometry(QtCore.QRect(0, 180, 921, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtGui.QFrame(GoalEntryDlg)
        self.line_3.setGeometry(QtCore.QRect(0, 380, 921, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.frame = QtGui.QFrame(GoalEntryDlg)
        self.frame.setGeometry(QtCore.QRect(10, 400, 411, 51))
        self.frame.setMinimumSize(QtCore.QSize(411, 51))
        self.frame.setMaximumSize(QtCore.QSize(411, 51))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.firstEntry = QtGui.QPushButton(self.frame)
        self.firstEntry.setGeometry(QtCore.QRect(10, 10, 90, 30))
        self.firstEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.firstEntry.setMaximumSize(QtCore.QSize(90, 30))
        self.firstEntry.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.firstEntry.setIcon(icon)
        self.firstEntry.setObjectName("firstEntry")
        self.prevEntry = QtGui.QPushButton(self.frame)
        self.prevEntry.setGeometry(QtCore.QRect(110, 10, 90, 30))
        self.prevEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.prevEntry.setMaximumSize(QtCore.QSize(90, 30))
        self.prevEntry.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevEntry.setIcon(icon1)
        self.prevEntry.setObjectName("prevEntry")
        self.nextEntry = QtGui.QPushButton(self.frame)
        self.nextEntry.setGeometry(QtCore.QRect(210, 10, 90, 30))
        self.nextEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.nextEntry.setMaximumSize(QtCore.QSize(90, 30))
        self.nextEntry.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextEntry.setIcon(icon2)
        self.nextEntry.setObjectName("nextEntry")
        self.lastEntry = QtGui.QPushButton(self.frame)
        self.lastEntry.setGeometry(QtCore.QRect(310, 10, 90, 30))
        self.lastEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.lastEntry.setMaximumSize(QtCore.QSize(90, 30))
        self.lastEntry.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lastEntry.setIcon(icon3)
        self.lastEntry.setObjectName("lastEntry")
        self.frame_2 = QtGui.QFrame(GoalEntryDlg)
        self.frame_2.setGeometry(QtCore.QRect(500, 400, 411, 51))
        self.frame_2.setMinimumSize(QtCore.QSize(411, 51))
        self.frame_2.setMaximumSize(QtCore.QSize(411, 51))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.addEntry = QtGui.QPushButton(self.frame_2)
        self.addEntry.setGeometry(QtCore.QRect(10, 10, 90, 30))
        self.addEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.addEntry.setMaximumSize(QtCore.QSize(90, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addEntry.setIcon(icon4)
        self.addEntry.setObjectName("addEntry")
        self.deleteEntry = QtGui.QPushButton(self.frame_2)
        self.deleteEntry.setGeometry(QtCore.QRect(110, 10, 90, 30))
        self.deleteEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.deleteEntry.setMaximumSize(QtCore.QSize(90, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteEntry.setIcon(icon5)
        self.deleteEntry.setObjectName("deleteEntry")
        self.saveEntry = QtGui.QPushButton(self.frame_2)
        self.saveEntry.setGeometry(QtCore.QRect(210, 10, 90, 30))
        self.saveEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.saveEntry.setMaximumSize(QtCore.QSize(90, 30))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveEntry.setIcon(icon6)
        self.saveEntry.setObjectName("saveEntry")
        self.closeButton = QtGui.QPushButton(self.frame_2)
        self.closeButton.setGeometry(QtCore.QRect(310, 10, 90, 30))
        self.closeButton.setMinimumSize(QtCore.QSize(90, 30))
        self.closeButton.setMaximumSize(QtCore.QSize(90, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon7)
        self.closeButton.setObjectName("closeButton")
        self.layoutWidget = QtGui.QWidget(GoalEntryDlg)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 1, 851, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(105, 30))
        self.label.setMaximumSize(QtCore.QSize(105, 30))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.compSelect = QtGui.QComboBox(self.layoutWidget)
        self.compSelect.setMinimumSize(QtCore.QSize(330, 30))
        self.compSelect.setMaximumSize(QtCore.QSize(330, 30))
        self.compSelect.setObjectName("compSelect")
        self.horizontalLayout_3.addWidget(self.compSelect)
        spacerItem = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(50, 30))
        self.label_11.setMaximumSize(QtCore.QSize(50, 30))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.phaseSelect = QtGui.QComboBox(self.layoutWidget)
        self.phaseSelect.setMinimumSize(QtCore.QSize(180, 30))
        self.phaseSelect.setMaximumSize(QtCore.QSize(180, 30))
        self.phaseSelect.setObjectName("phaseSelect")
        self.horizontalLayout_3.addWidget(self.phaseSelect)
        self.layoutWidget1 = QtGui.QWidget(GoalEntryDlg)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 200, 901, 181))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(105, 30))
        self.label_3.setMaximumSize(QtCore.QSize(105, 30))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.matchSelect = QtGui.QComboBox(self.layoutWidget1)
        self.matchSelect.setMinimumSize(QtCore.QSize(330, 30))
        self.matchSelect.setMaximumSize(QtCore.QSize(330, 30))
        self.matchSelect.setObjectName("matchSelect")
        self.gridLayout.addWidget(self.matchSelect, 0, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(105, 30))
        self.label_4.setMaximumSize(QtCore.QSize(105, 30))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.goalID_display = QtGui.QLineEdit(self.layoutWidget1)
        self.goalID_display.setMinimumSize(QtCore.QSize(120, 30))
        self.goalID_display.setMaximumSize(QtCore.QSize(120, 30))
        self.goalID_display.setStyleSheet("background-color: rgb(194, 190, 186);")
        self.goalID_display.setMaxLength(7)
        self.goalID_display.setReadOnly(True)
        self.goalID_display.setObjectName("goalID_display")
        self.gridLayout.addWidget(self.goalID_display, 0, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(105, 30))
        self.label_5.setMaximumSize(QtCore.QSize(105, 30))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.teamSelect = QtGui.QComboBox(self.layoutWidget1)
        self.teamSelect.setMinimumSize(QtCore.QSize(300, 30))
        self.teamSelect.setMaximumSize(QtCore.QSize(300, 30))
        self.teamSelect.setObjectName("teamSelect")
        self.gridLayout.addWidget(self.teamSelect, 1, 1, 1, 2)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setMinimumSize(QtCore.QSize(105, 30))
        self.label_10.setMaximumSize(QtCore.QSize(105, 30))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 3, 1, 1)
        self.playerSelect = QtGui.QComboBox(self.layoutWidget1)
        self.playerSelect.setMinimumSize(QtCore.QSize(300, 30))
        self.playerSelect.setMaximumSize(QtCore.QSize(300, 30))
        self.playerSelect.setObjectName("playerSelect")
        self.gridLayout.addWidget(self.playerSelect, 1, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setMinimumSize(QtCore.QSize(105, 30))
        self.label_7.setMaximumSize(QtCore.QSize(105, 30))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.goaleventSelect = QtGui.QComboBox(self.layoutWidget1)
        self.goaleventSelect.setMinimumSize(QtCore.QSize(300, 30))
        self.goaleventSelect.setMaximumSize(QtCore.QSize(300, 30))
        self.goaleventSelect.setObjectName("goaleventSelect")
        self.gridLayout.addWidget(self.goaleventSelect, 2, 1, 1, 2)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(105, 30))
        self.label_6.setMaximumSize(QtCore.QSize(105, 30))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 3, 1, 1)
        self.goaltypeSelect = QtGui.QComboBox(self.layoutWidget1)
        self.goaltypeSelect.setMinimumSize(QtCore.QSize(300, 30))
        self.goaltypeSelect.setMaximumSize(QtCore.QSize(300, 30))
        self.goaltypeSelect.setObjectName("goaltypeSelect")
        self.gridLayout.addWidget(self.goaltypeSelect, 2, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setMinimumSize(QtCore.QSize(105, 30))
        self.label_8.setMaximumSize(QtCore.QSize(105, 30))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.goaltimeEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.goaltimeEdit.setMinimumSize(QtCore.QSize(41, 27))
        self.goaltimeEdit.setMaximumSize(QtCore.QSize(41, 27))
        self.goaltimeEdit.setInputMask("")
        self.goaltimeEdit.setMaxLength(3)
        self.goaltimeEdit.setObjectName("goaltimeEdit")
        self.horizontalLayout.addWidget(self.goaltimeEdit)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.stoppageEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.stoppageEdit.setMinimumSize(QtCore.QSize(41, 27))
        self.stoppageEdit.setMaximumSize(QtCore.QSize(41, 27))
        self.stoppageEdit.setInputMask("")
        self.stoppageEdit.setMaxLength(2)
        self.stoppageEdit.setObjectName("stoppageEdit")
        self.horizontalLayout.addWidget(self.stoppageEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(398, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 3, 1, 2)
        self.layoutWidget2 = QtGui.QWidget(GoalEntryDlg)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 60, 871, 131))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.leagueBox = QtGui.QGroupBox(self.layoutWidget2)
        self.leagueBox.setMinimumSize(QtCore.QSize(270, 60))
        self.leagueBox.setMaximumSize(QtCore.QSize(270, 60))
        self.leagueBox.setObjectName("leagueBox")
        self.label_2 = QtGui.QLabel(self.leagueBox)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 50, 30))
        self.label_2.setMinimumSize(QtCore.QSize(50, 30))
        self.label_2.setMaximumSize(QtCore.QSize(50, 30))
        self.label_2.setObjectName("label_2")
        self.lgRoundSelect = QtGui.QComboBox(self.leagueBox)
        self.lgRoundSelect.setGeometry(QtCore.QRect(80, 20, 180, 30))
        self.lgRoundSelect.setMinimumSize(QtCore.QSize(180, 30))
        self.lgRoundSelect.setMaximumSize(QtCore.QSize(180, 30))
        self.lgRoundSelect.setObjectName("lgRoundSelect")
        self.gridLayout_2.addWidget(self.leagueBox, 0, 0, 1, 1)
        self.knockoutBox = QtGui.QGroupBox(self.layoutWidget2)
        self.knockoutBox.setMinimumSize(QtCore.QSize(330, 60))
        self.knockoutBox.setMaximumSize(QtCore.QSize(585, 100))
        self.knockoutBox.setObjectName("knockoutBox")
        self.label_12 = QtGui.QLabel(self.knockoutBox)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 50, 30))
        self.label_12.setMinimumSize(QtCore.QSize(50, 30))
        self.label_12.setMaximumSize(QtCore.QSize(50, 30))
        self.label_12.setObjectName("label_12")
        self.koRoundSelect = QtGui.QComboBox(self.knockoutBox)
        self.koRoundSelect.setGeometry(QtCore.QRect(60, 20, 240, 30))
        self.koRoundSelect.setMinimumSize(QtCore.QSize(240, 30))
        self.koRoundSelect.setMaximumSize(QtCore.QSize(240, 30))
        self.koRoundSelect.setObjectName("koRoundSelect")
        self.koMatchdaySelect = QtGui.QComboBox(self.knockoutBox)
        self.koMatchdaySelect.setGeometry(QtCore.QRect(390, 20, 180, 30))
        self.koMatchdaySelect.setMinimumSize(QtCore.QSize(180, 30))
        self.koMatchdaySelect.setMaximumSize(QtCore.QSize(180, 30))
        self.koMatchdaySelect.setObjectName("koMatchdaySelect")
        self.label_13 = QtGui.QLabel(self.knockoutBox)
        self.label_13.setGeometry(QtCore.QRect(310, 20, 75, 30))
        self.label_13.setMinimumSize(QtCore.QSize(75, 30))
        self.label_13.setMaximumSize(QtCore.QSize(75, 30))
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.knockoutBox, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget2)
        self.groupBox.setMinimumSize(QtCore.QSize(280, 50))
        self.groupBox.setMaximumSize(QtCore.QSize(940, 100))
        self.groupBox.setObjectName("groupBox")
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 50, 30))
        self.label_14.setMinimumSize(QtCore.QSize(50, 30))
        self.label_14.setMaximumSize(QtCore.QSize(50, 30))
        self.label_14.setObjectName("label_14")
        self.grpRoundSelect = QtGui.QComboBox(self.groupBox)
        self.grpRoundSelect.setGeometry(QtCore.QRect(80, 20, 240, 30))
        self.grpRoundSelect.setMinimumSize(QtCore.QSize(240, 30))
        self.grpRoundSelect.setMaximumSize(QtCore.QSize(240, 30))
        self.grpRoundSelect.setObjectName("grpRoundSelect")
        self.grpMatchdaySelect = QtGui.QComboBox(self.groupBox)
        self.grpMatchdaySelect.setGeometry(QtCore.QRect(670, 20, 180, 30))
        self.grpMatchdaySelect.setMinimumSize(QtCore.QSize(180, 30))
        self.grpMatchdaySelect.setMaximumSize(QtCore.QSize(180, 30))
        self.grpMatchdaySelect.setObjectName("grpMatchdaySelect")
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(590, 20, 75, 30))
        self.label_16.setMinimumSize(QtCore.QSize(75, 30))
        self.label_16.setMaximumSize(QtCore.QSize(75, 30))
        self.label_16.setObjectName("label_16")
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(390, 20, 50, 30))
        self.label_15.setMinimumSize(QtCore.QSize(50, 30))
        self.label_15.setMaximumSize(QtCore.QSize(50, 30))
        self.label_15.setObjectName("label_15")
        self.groupSelect = QtGui.QComboBox(self.groupBox)
        self.groupSelect.setGeometry(QtCore.QRect(440, 20, 60, 30))
        self.groupSelect.setMinimumSize(QtCore.QSize(60, 30))
        self.groupSelect.setMaximumSize(QtCore.QSize(60, 30))
        self.groupSelect.setObjectName("groupSelect")
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 2)

        self.retranslateUi(GoalEntryDlg)
        QtCore.QMetaObject.connectSlotsByName(GoalEntryDlg)

    def retranslateUi(self, GoalEntryDlg):
        GoalEntryDlg.setWindowTitle(QtGui.QApplication.translate("GoalEntryDlg", "Goal Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.firstEntry.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "First Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.prevEntry.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Previous Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.nextEntry.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Next Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.lastEntry.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Last Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.addEntry.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Add Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.addEntry.setText(QtGui.QApplication.translate("GoalEntryDlg", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEntry.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Delete Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEntry.setText(QtGui.QApplication.translate("GoalEntryDlg", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.saveEntry.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Save Entry to Database", None, QtGui.QApplication.UnicodeUTF8))
        self.saveEntry.setText(QtGui.QApplication.translate("GoalEntryDlg", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Close Window", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("GoalEntryDlg", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Competition</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.compSelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Competition Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Phase</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseSelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Competition Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Match</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchSelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Football Match", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Goal ID</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Team</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.teamSelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Team to which goal is credited", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Player</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.playerSelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Goal scorer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Match Event</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.goaleventSelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Field event from which goal is scored", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">How Scored</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.goaltypeSelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Body part used to score open play goals", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Match Time</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.goaltimeEdit.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Match time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">+</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.stoppageEdit.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Stoppage time", None, QtGui.QApplication.UnicodeUTF8))
        self.leagueBox.setTitle(QtGui.QApplication.translate("GoalEntryDlg", "League Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Round</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lgRoundSelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "League Round", None, QtGui.QApplication.UnicodeUTF8))
        self.knockoutBox.setTitle(QtGui.QApplication.translate("GoalEntryDlg", "Knockout Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Round</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.koRoundSelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Knockout Round", None, QtGui.QApplication.UnicodeUTF8))
        self.koMatchdaySelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Knockout Round Matchday", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Matchday</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("GoalEntryDlg", "Group Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Round</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.grpRoundSelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Group Phase Round", None, QtGui.QApplication.UnicodeUTF8))
        self.grpMatchdaySelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Group Round Matchday", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Matchday</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("GoalEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Group</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupSelect.setToolTip(QtGui.QApplication.translate("GoalEntryDlg", "Group Name", None, QtGui.QApplication.UnicodeUTF8))

import fmrd_resources_rc
