# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/main_switchboard.ui'
#
# Created: Fri Aug  5 15:10:54 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainSwitchboard(object):
    def setupUi(self, MainSwitchboard):
        MainSwitchboard.setObjectName("MainSwitchboard")
        MainSwitchboard.resize(360, 420)
        MainSwitchboard.setMinimumSize(QtCore.QSize(360, 420))
        MainSwitchboard.setMaximumSize(QtCore.QSize(360, 420))
        self.centralwidget = QtGui.QWidget(MainSwitchboard)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.compButton = QtGui.QPushButton(self.groupBox)
        self.compButton.setObjectName("compButton")
        self.verticalLayout.addWidget(self.compButton)
        self.teamButton = QtGui.QPushButton(self.groupBox)
        self.teamButton.setObjectName("teamButton")
        self.verticalLayout.addWidget(self.teamButton)
        self.venueButton = QtGui.QPushButton(self.groupBox)
        self.venueButton.setObjectName("venueButton")
        self.verticalLayout.addWidget(self.venueButton)
        self.verticalLayout_4.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.playerButton = QtGui.QPushButton(self.groupBox_2)
        self.playerButton.setObjectName("playerButton")
        self.verticalLayout_2.addWidget(self.playerButton)
        self.refereeButton = QtGui.QPushButton(self.groupBox_2)
        self.refereeButton.setObjectName("refereeButton")
        self.verticalLayout_2.addWidget(self.refereeButton)
        self.managerButton = QtGui.QPushButton(self.groupBox_2)
        self.managerButton.setObjectName("managerButton")
        self.verticalLayout_2.addWidget(self.managerButton)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.matchButton = QtGui.QPushButton(self.groupBox_3)
        self.matchButton.setObjectName("matchButton")
        self.verticalLayout_3.addWidget(self.matchButton)
        self.goalButton = QtGui.QPushButton(self.groupBox_3)
        self.goalButton.setObjectName("goalButton")
        self.verticalLayout_3.addWidget(self.goalButton)
        self.penButton = QtGui.QPushButton(self.groupBox_3)
        self.penButton.setObjectName("penButton")
        self.verticalLayout_3.addWidget(self.penButton)
        self.offenseButton = QtGui.QPushButton(self.groupBox_3)
        self.offenseButton.setObjectName("offenseButton")
        self.verticalLayout_3.addWidget(self.offenseButton)
        self.subButton = QtGui.QPushButton(self.groupBox_3)
        self.subButton.setObjectName("subButton")
        self.verticalLayout_3.addWidget(self.subButton)
        self.switchButton = QtGui.QPushButton(self.groupBox_3)
        self.switchButton.setObjectName("switchButton")
        self.verticalLayout_3.addWidget(self.switchButton)
        self.gridLayout.addWidget(self.groupBox_3, 0, 2, 1, 1)
        MainSwitchboard.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainSwitchboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 23))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtGui.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuSetup = QtGui.QMenu(self.menubar)
        self.menuSetup.setObjectName("menuSetup")
        self.menuOverview = QtGui.QMenu(self.menuSetup)
        self.menuOverview.setObjectName("menuOverview")
        self.menuPersonnel = QtGui.QMenu(self.menuSetup)
        self.menuPersonnel.setObjectName("menuPersonnel")
        self.menuEvents = QtGui.QMenu(self.menuSetup)
        self.menuEvents.setObjectName("menuEvents")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainSwitchboard.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainSwitchboard)
        self.statusbar.setObjectName("statusbar")
        MainSwitchboard.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainSwitchboard)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(MainSwitchboard)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRounds = QtGui.QAction(MainSwitchboard)
        self.actionRounds.setObjectName("actionRounds")
        self.actionWeather_Conditions = QtGui.QAction(MainSwitchboard)
        self.actionWeather_Conditions.setObjectName("actionWeather_Conditions")
        self.actionConfederations = QtGui.QAction(MainSwitchboard)
        self.actionConfederations.setObjectName("actionConfederations")
        self.actionCountries = QtGui.QAction(MainSwitchboard)
        self.actionCountries.setObjectName("actionCountries")
        self.actionField_Positions = QtGui.QAction(MainSwitchboard)
        self.actionField_Positions.setObjectName("actionField_Positions")
        self.actionFlank_Positions = QtGui.QAction(MainSwitchboard)
        self.actionFlank_Positions.setObjectName("actionFlank_Positions")
        self.actionPositions = QtGui.QAction(MainSwitchboard)
        self.actionPositions.setObjectName("actionPositions")
        self.actionGoal_Events = QtGui.QAction(MainSwitchboard)
        self.actionGoal_Events.setObjectName("actionGoal_Events")
        self.actionGoal_Strikes = QtGui.QAction(MainSwitchboard)
        self.actionGoal_Strikes.setObjectName("actionGoal_Strikes")
        self.actionPenalty_Outcomes = QtGui.QAction(MainSwitchboard)
        self.actionPenalty_Outcomes.setObjectName("actionPenalty_Outcomes")
        self.actionFouls = QtGui.QAction(MainSwitchboard)
        self.actionFouls.setObjectName("actionFouls")
        self.actionCards = QtGui.QAction(MainSwitchboard)
        self.actionCards.setObjectName("actionCards")
        self.menuMain.addAction(self.actionQuit)
        self.menuOverview.addAction(self.actionRounds)
        self.menuOverview.addAction(self.actionWeather_Conditions)
        self.menuPersonnel.addAction(self.actionConfederations)
        self.menuPersonnel.addAction(self.actionCountries)
        self.menuPersonnel.addAction(self.actionField_Positions)
        self.menuPersonnel.addAction(self.actionFlank_Positions)
        self.menuPersonnel.addAction(self.actionPositions)
        self.menuEvents.addAction(self.actionGoal_Events)
        self.menuEvents.addAction(self.actionGoal_Strikes)
        self.menuEvents.addAction(self.actionPenalty_Outcomes)
        self.menuEvents.addAction(self.actionFouls)
        self.menuEvents.addAction(self.actionCards)
        self.menuSetup.addAction(self.menuOverview.menuAction())
        self.menuSetup.addAction(self.menuPersonnel.menuAction())
        self.menuSetup.addAction(self.menuEvents.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuSetup.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainSwitchboard)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), MainSwitchboard.close)
        QtCore.QMetaObject.connectSlotsByName(MainSwitchboard)

    def retranslateUi(self, MainSwitchboard):
        MainSwitchboard.setWindowTitle(QtGui.QApplication.translate("MainSwitchboard", "FMRD Switchboard", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainSwitchboard", "Match Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.compButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Competitions", None, QtGui.QApplication.UnicodeUTF8))
        self.teamButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Teams", None, QtGui.QApplication.UnicodeUTF8))
        self.venueButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Venues", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainSwitchboard", "Personnel", None, QtGui.QApplication.UnicodeUTF8))
        self.playerButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Players", None, QtGui.QApplication.UnicodeUTF8))
        self.refereeButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Referees", None, QtGui.QApplication.UnicodeUTF8))
        self.managerButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Managers", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainSwitchboard", "Match Details", None, QtGui.QApplication.UnicodeUTF8))
        self.matchButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.goalButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Goals", None, QtGui.QApplication.UnicodeUTF8))
        self.penButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Penalties", None, QtGui.QApplication.UnicodeUTF8))
        self.offenseButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Offenses", None, QtGui.QApplication.UnicodeUTF8))
        self.subButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Substitutions", None, QtGui.QApplication.UnicodeUTF8))
        self.switchButton.setText(QtGui.QApplication.translate("MainSwitchboard", "Position Switches", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMain.setTitle(QtGui.QApplication.translate("MainSwitchboard", "&Main", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSetup.setTitle(QtGui.QApplication.translate("MainSwitchboard", "&Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOverview.setTitle(QtGui.QApplication.translate("MainSwitchboard", "&Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPersonnel.setTitle(QtGui.QApplication.translate("MainSwitchboard", "&Personnel", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEvents.setTitle(QtGui.QApplication.translate("MainSwitchboard", "&Events", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainSwitchboard", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainSwitchboard", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainSwitchboard", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainSwitchboard", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("MainSwitchboard", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRounds.setText(QtGui.QApplication.translate("MainSwitchboard", "Rounds", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWeather_Conditions.setText(QtGui.QApplication.translate("MainSwitchboard", "Weather Conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfederations.setText(QtGui.QApplication.translate("MainSwitchboard", "Confederations", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCountries.setText(QtGui.QApplication.translate("MainSwitchboard", "Countries", None, QtGui.QApplication.UnicodeUTF8))
        self.actionField_Positions.setText(QtGui.QApplication.translate("MainSwitchboard", "Field Positions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFlank_Positions.setText(QtGui.QApplication.translate("MainSwitchboard", "Flank Positions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPositions.setText(QtGui.QApplication.translate("MainSwitchboard", "Positions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoal_Events.setText(QtGui.QApplication.translate("MainSwitchboard", "Goal Events", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoal_Strikes.setText(QtGui.QApplication.translate("MainSwitchboard", "Goal Strikes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPenalty_Outcomes.setText(QtGui.QApplication.translate("MainSwitchboard", "Penalty Outcomes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFouls.setText(QtGui.QApplication.translate("MainSwitchboard", "Fouls", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCards.setText(QtGui.QApplication.translate("MainSwitchboard", "Cards", None, QtGui.QApplication.UnicodeUTF8))

