# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/match_entry.ui'
#
# Created: Mon Dec  5 22:10:33 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MatchEntryDlg(object):
    def setupUi(self, MatchEntryDlg):
        MatchEntryDlg.setObjectName("MatchEntryDlg")
        MatchEntryDlg.resize(930, 600)
        MatchEntryDlg.setMinimumSize(QtCore.QSize(930, 600))
        MatchEntryDlg.setMaximumSize(QtCore.QSize(930, 600))
        self.line = QtGui.QFrame(MatchEntryDlg)
        self.line.setGeometry(QtCore.QRect(0, 90, 911, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtGui.QFrame(MatchEntryDlg)
        self.line_3.setGeometry(QtCore.QRect(0, 510, 921, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.matchID_display = QtGui.QLineEdit(MatchEntryDlg)
        self.matchID_display.setGeometry(QtCore.QRect(82, 9, 120, 30))
        self.matchID_display.setMinimumSize(QtCore.QSize(120, 30))
        self.matchID_display.setMaximumSize(QtCore.QSize(120, 30))
        self.matchID_display.setStyleSheet("background-color: rgb(194, 190, 186);")
        self.matchID_display.setMaxLength(7)
        self.matchID_display.setReadOnly(True)
        self.matchID_display.setObjectName("matchID_display")
        self.label = QtGui.QLabel(MatchEntryDlg)
        self.label.setGeometry(QtCore.QRect(9, 9, 75, 30))
        self.label.setMinimumSize(QtCore.QSize(75, 30))
        self.label.setMaximumSize(QtCore.QSize(75, 30))
        self.label.setObjectName("label")
        self.frame = QtGui.QFrame(MatchEntryDlg)
        self.frame.setGeometry(QtCore.QRect(10, 530, 411, 51))
        self.frame.setMinimumSize(QtCore.QSize(411, 51))
        self.frame.setMaximumSize(QtCore.QSize(411, 51))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.firstEntry = QtGui.QPushButton(self.frame)
        self.firstEntry.setGeometry(QtCore.QRect(10, 10, 90, 30))
        self.firstEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.firstEntry.setMaximumSize(QtCore.QSize(90, 30))
        self.firstEntry.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.firstEntry.setIcon(icon)
        self.firstEntry.setObjectName("firstEntry")
        self.prevEntry = QtGui.QPushButton(self.frame)
        self.prevEntry.setGeometry(QtCore.QRect(110, 10, 90, 30))
        self.prevEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.prevEntry.setMaximumSize(QtCore.QSize(90, 30))
        self.prevEntry.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevEntry.setIcon(icon1)
        self.prevEntry.setObjectName("prevEntry")
        self.nextEntry = QtGui.QPushButton(self.frame)
        self.nextEntry.setGeometry(QtCore.QRect(210, 10, 90, 30))
        self.nextEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.nextEntry.setMaximumSize(QtCore.QSize(90, 30))
        self.nextEntry.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextEntry.setIcon(icon2)
        self.nextEntry.setObjectName("nextEntry")
        self.lastEntry = QtGui.QPushButton(self.frame)
        self.lastEntry.setGeometry(QtCore.QRect(310, 10, 90, 30))
        self.lastEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.lastEntry.setMaximumSize(QtCore.QSize(90, 30))
        self.lastEntry.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lastEntry.setIcon(icon3)
        self.lastEntry.setObjectName("lastEntry")
        self.frame_2 = QtGui.QFrame(MatchEntryDlg)
        self.frame_2.setGeometry(QtCore.QRect(500, 530, 411, 51))
        self.frame_2.setMinimumSize(QtCore.QSize(411, 51))
        self.frame_2.setMaximumSize(QtCore.QSize(411, 51))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.addEntry = QtGui.QPushButton(self.frame_2)
        self.addEntry.setGeometry(QtCore.QRect(10, 10, 90, 30))
        self.addEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.addEntry.setMaximumSize(QtCore.QSize(90, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addEntry.setIcon(icon4)
        self.addEntry.setObjectName("addEntry")
        self.deleteEntry = QtGui.QPushButton(self.frame_2)
        self.deleteEntry.setGeometry(QtCore.QRect(110, 10, 90, 30))
        self.deleteEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.deleteEntry.setMaximumSize(QtCore.QSize(90, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteEntry.setIcon(icon5)
        self.deleteEntry.setObjectName("deleteEntry")
        self.saveEntry = QtGui.QPushButton(self.frame_2)
        self.saveEntry.setGeometry(QtCore.QRect(210, 10, 90, 30))
        self.saveEntry.setMinimumSize(QtCore.QSize(90, 30))
        self.saveEntry.setMaximumSize(QtCore.QSize(90, 30))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveEntry.setIcon(icon6)
        self.saveEntry.setObjectName("saveEntry")
        self.closeButton = QtGui.QPushButton(self.frame_2)
        self.closeButton.setGeometry(QtCore.QRect(310, 10, 90, 30))
        self.closeButton.setMinimumSize(QtCore.QSize(90, 30))
        self.closeButton.setMaximumSize(QtCore.QSize(90, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon7)
        self.closeButton.setObjectName("closeButton")
        self.layoutWidget = QtGui.QWidget(MatchEntryDlg)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 110, 871, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.leagueBox = QtGui.QGroupBox(self.layoutWidget)
        self.leagueBox.setMinimumSize(QtCore.QSize(270, 60))
        self.leagueBox.setMaximumSize(QtCore.QSize(270, 60))
        self.leagueBox.setObjectName("leagueBox")
        self.label_2 = QtGui.QLabel(self.leagueBox)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 50, 30))
        self.label_2.setMinimumSize(QtCore.QSize(50, 30))
        self.label_2.setMaximumSize(QtCore.QSize(50, 30))
        self.label_2.setObjectName("label_2")
        self.lgRoundSelect = QtGui.QComboBox(self.leagueBox)
        self.lgRoundSelect.setGeometry(QtCore.QRect(80, 20, 180, 30))
        self.lgRoundSelect.setMinimumSize(QtCore.QSize(180, 30))
        self.lgRoundSelect.setMaximumSize(QtCore.QSize(180, 30))
        self.lgRoundSelect.setObjectName("lgRoundSelect")
        self.gridLayout_3.addWidget(self.leagueBox, 0, 0, 1, 1)
        self.knockoutBox = QtGui.QGroupBox(self.layoutWidget)
        self.knockoutBox.setMinimumSize(QtCore.QSize(330, 60))
        self.knockoutBox.setMaximumSize(QtCore.QSize(585, 100))
        self.knockoutBox.setObjectName("knockoutBox")
        self.label_17 = QtGui.QLabel(self.knockoutBox)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 50, 30))
        self.label_17.setMinimumSize(QtCore.QSize(50, 30))
        self.label_17.setMaximumSize(QtCore.QSize(50, 30))
        self.label_17.setObjectName("label_17")
        self.koRoundSelect = QtGui.QComboBox(self.knockoutBox)
        self.koRoundSelect.setGeometry(QtCore.QRect(60, 20, 240, 30))
        self.koRoundSelect.setMinimumSize(QtCore.QSize(240, 30))
        self.koRoundSelect.setMaximumSize(QtCore.QSize(240, 30))
        self.koRoundSelect.setObjectName("koRoundSelect")
        self.koMatchdaySelect = QtGui.QComboBox(self.knockoutBox)
        self.koMatchdaySelect.setGeometry(QtCore.QRect(390, 20, 180, 30))
        self.koMatchdaySelect.setMinimumSize(QtCore.QSize(180, 30))
        self.koMatchdaySelect.setMaximumSize(QtCore.QSize(180, 30))
        self.koMatchdaySelect.setObjectName("koMatchdaySelect")
        self.label_18 = QtGui.QLabel(self.knockoutBox)
        self.label_18.setGeometry(QtCore.QRect(310, 20, 75, 30))
        self.label_18.setMinimumSize(QtCore.QSize(75, 30))
        self.label_18.setMaximumSize(QtCore.QSize(75, 30))
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.knockoutBox, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(280, 50))
        self.groupBox.setMaximumSize(QtCore.QSize(940, 100))
        self.groupBox.setObjectName("groupBox")
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(290, 20, 50, 30))
        self.label_19.setMinimumSize(QtCore.QSize(50, 30))
        self.label_19.setMaximumSize(QtCore.QSize(50, 30))
        self.label_19.setObjectName("label_19")
        self.grpRoundSelect = QtGui.QComboBox(self.groupBox)
        self.grpRoundSelect.setGeometry(QtCore.QRect(340, 20, 240, 30))
        self.grpRoundSelect.setMinimumSize(QtCore.QSize(240, 30))
        self.grpRoundSelect.setMaximumSize(QtCore.QSize(240, 30))
        self.grpRoundSelect.setObjectName("grpRoundSelect")
        self.groupSelect = QtGui.QComboBox(self.groupBox)
        self.groupSelect.setGeometry(QtCore.QRect(80, 20, 60, 30))
        self.groupSelect.setMinimumSize(QtCore.QSize(60, 30))
        self.groupSelect.setMaximumSize(QtCore.QSize(60, 30))
        self.groupSelect.setObjectName("groupSelect")
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(20, 20, 50, 30))
        self.label_20.setMinimumSize(QtCore.QSize(50, 30))
        self.label_20.setMaximumSize(QtCore.QSize(50, 30))
        self.label_20.setObjectName("label_20")
        self.grpMatchdaySelect = QtGui.QComboBox(self.groupBox)
        self.grpMatchdaySelect.setGeometry(QtCore.QRect(670, 20, 180, 30))
        self.grpMatchdaySelect.setMinimumSize(QtCore.QSize(180, 30))
        self.grpMatchdaySelect.setMaximumSize(QtCore.QSize(180, 30))
        self.grpMatchdaySelect.setObjectName("grpMatchdaySelect")
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(590, 20, 75, 30))
        self.label_21.setMinimumSize(QtCore.QSize(75, 30))
        self.label_21.setMaximumSize(QtCore.QSize(75, 30))
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 2)
        self.matchtimeBox = QtGui.QGroupBox(MatchEntryDlg)
        self.matchtimeBox.setGeometry(QtCore.QRect(550, 250, 291, 111))
        self.matchtimeBox.setObjectName("matchtimeBox")
        self.layoutWidget1 = QtGui.QWidget(self.matchtimeBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 20, 215, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setMinimumSize(QtCore.QSize(60, 30))
        self.label_11.setMaximumSize(QtCore.QSize(60, 30))
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.firstHalfLengthEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.firstHalfLengthEdit.setMinimumSize(QtCore.QSize(30, 30))
        self.firstHalfLengthEdit.setMaximumSize(QtCore.QSize(30, 30))
        self.firstHalfLengthEdit.setMaxLength(2)
        self.firstHalfLengthEdit.setObjectName("firstHalfLengthEdit")
        self.gridLayout_4.addWidget(self.firstHalfLengthEdit, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setMinimumSize(QtCore.QSize(75, 30))
        self.label_12.setMaximumSize(QtCore.QSize(75, 30))
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 2, 1, 1)
        self.secondHalfLengthEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.secondHalfLengthEdit.setMinimumSize(QtCore.QSize(30, 30))
        self.secondHalfLengthEdit.setMaximumSize(QtCore.QSize(30, 30))
        self.secondHalfLengthEdit.setMaxLength(2)
        self.secondHalfLengthEdit.setObjectName("secondHalfLengthEdit")
        self.gridLayout_4.addWidget(self.secondHalfLengthEdit, 0, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        self.label_15.setMinimumSize(QtCore.QSize(60, 30))
        self.label_15.setMaximumSize(QtCore.QSize(60, 30))
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 0, 1, 1)
        self.firstExtraLengthEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.firstExtraLengthEdit.setMinimumSize(QtCore.QSize(30, 30))
        self.firstExtraLengthEdit.setMaximumSize(QtCore.QSize(30, 30))
        self.firstExtraLengthEdit.setMaxLength(2)
        self.firstExtraLengthEdit.setObjectName("firstExtraLengthEdit")
        self.gridLayout_4.addWidget(self.firstExtraLengthEdit, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget1)
        self.label_16.setMinimumSize(QtCore.QSize(60, 30))
        self.label_16.setMaximumSize(QtCore.QSize(60, 30))
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 2, 1, 1)
        self.secondExtraLengthEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.secondExtraLengthEdit.setMinimumSize(QtCore.QSize(30, 30))
        self.secondExtraLengthEdit.setMaximumSize(QtCore.QSize(30, 30))
        self.secondExtraLengthEdit.setMaxLength(2)
        self.secondExtraLengthEdit.setObjectName("secondExtraLengthEdit")
        self.gridLayout_4.addWidget(self.secondExtraLengthEdit, 1, 3, 1, 1)
        self.line_4 = QtGui.QFrame(MatchEntryDlg)
        self.line_4.setGeometry(QtCore.QRect(0, 370, 921, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.hometeamBox = QtGui.QGroupBox(MatchEntryDlg)
        self.hometeamBox.setGeometry(QtCore.QRect(10, 380, 341, 141))
        self.hometeamBox.setObjectName("hometeamBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.hometeamBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtGui.QLabel(self.hometeamBox)
        self.label_8.setMinimumSize(QtCore.QSize(86, 31))
        self.label_8.setMaximumSize(QtCore.QSize(86, 31))
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.homemgrSelect = QtGui.QComboBox(self.hometeamBox)
        self.homemgrSelect.setEnabled(True)
        self.homemgrSelect.setMinimumSize(QtCore.QSize(221, 31))
        self.homemgrSelect.setMaximumSize(QtCore.QSize(221, 31))
        self.homemgrSelect.setObjectName("homemgrSelect")
        self.gridLayout_2.addWidget(self.homemgrSelect, 2, 1, 1, 1)
        self.hometeamSelect = QtGui.QComboBox(self.hometeamBox)
        self.hometeamSelect.setMinimumSize(QtCore.QSize(221, 31))
        self.hometeamSelect.setMaximumSize(QtCore.QSize(221, 31))
        self.hometeamSelect.setObjectName("hometeamSelect")
        self.gridLayout_2.addWidget(self.hometeamSelect, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.hometeamBox)
        self.label_7.setMinimumSize(QtCore.QSize(86, 31))
        self.label_7.setMaximumSize(QtCore.QSize(86, 31))
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.homeLineupButton = QtGui.QPushButton(self.hometeamBox)
        self.homeLineupButton.setEnabled(True)
        self.homeLineupButton.setMinimumSize(QtCore.QSize(120, 30))
        self.homeLineupButton.setMaximumSize(QtCore.QSize(120, 30))
        self.homeLineupButton.setObjectName("homeLineupButton")
        self.gridLayout_2.addWidget(self.homeLineupButton, 3, 1, 1, 1)
        self.awayteamBox = QtGui.QGroupBox(MatchEntryDlg)
        self.awayteamBox.setGeometry(QtCore.QRect(550, 380, 339, 141))
        self.awayteamBox.setObjectName("awayteamBox")
        self.gridLayout = QtGui.QGridLayout(self.awayteamBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtGui.QLabel(self.awayteamBox)
        self.label_9.setMinimumSize(QtCore.QSize(86, 31))
        self.label_9.setMaximumSize(QtCore.QSize(86, 31))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.awayteamSelect = QtGui.QComboBox(self.awayteamBox)
        self.awayteamSelect.setEnabled(True)
        self.awayteamSelect.setMinimumSize(QtCore.QSize(221, 31))
        self.awayteamSelect.setMaximumSize(QtCore.QSize(221, 31))
        self.awayteamSelect.setObjectName("awayteamSelect")
        self.gridLayout.addWidget(self.awayteamSelect, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.awayteamBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.awaymgrSelect = QtGui.QComboBox(self.awayteamBox)
        self.awaymgrSelect.setEnabled(True)
        self.awaymgrSelect.setMinimumSize(QtCore.QSize(221, 31))
        self.awaymgrSelect.setMaximumSize(QtCore.QSize(221, 31))
        self.awaymgrSelect.setObjectName("awaymgrSelect")
        self.gridLayout.addWidget(self.awaymgrSelect, 1, 1, 1, 1)
        self.awayLineupButton = QtGui.QPushButton(self.awayteamBox)
        self.awayLineupButton.setEnabled(True)
        self.awayLineupButton.setMinimumSize(QtCore.QSize(120, 30))
        self.awayLineupButton.setMaximumSize(QtCore.QSize(120, 30))
        self.awayLineupButton.setObjectName("awayLineupButton")
        self.gridLayout.addWidget(self.awayLineupButton, 2, 1, 1, 1)
        self.enviroButton = QtGui.QPushButton(MatchEntryDlg)
        self.enviroButton.setGeometry(QtCore.QRect(390, 430, 120, 30))
        self.enviroButton.setMinimumSize(QtCore.QSize(120, 30))
        self.enviroButton.setMaximumSize(QtCore.QSize(120, 30))
        self.enviroButton.setDefault(False)
        self.enviroButton.setObjectName("enviroButton")
        self.layoutWidget2 = QtGui.QWidget(MatchEntryDlg)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 240, 481, 141))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setMinimumSize(QtCore.QSize(75, 30))
        self.label_5.setMaximumSize(QtCore.QSize(75, 30))
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.matchVenueSelect = QtGui.QComboBox(self.layoutWidget2)
        self.matchVenueSelect.setMinimumSize(QtCore.QSize(360, 30))
        self.matchVenueSelect.setMaximumSize(QtCore.QSize(360, 30))
        self.matchVenueSelect.setObjectName("matchVenueSelect")
        self.gridLayout_5.addWidget(self.matchVenueSelect, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setMinimumSize(QtCore.QSize(75, 30))
        self.label_6.setMaximumSize(QtCore.QSize(75, 30))
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.matchRefSelect = QtGui.QComboBox(self.layoutWidget2)
        self.matchRefSelect.setMinimumSize(QtCore.QSize(330, 30))
        self.matchRefSelect.setMaximumSize(QtCore.QSize(330, 30))
        self.matchRefSelect.setObjectName("matchRefSelect")
        self.gridLayout_5.addWidget(self.matchRefSelect, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget2)
        self.label_22.setMinimumSize(QtCore.QSize(90, 30))
        self.label_22.setMaximumSize(QtCore.QSize(90, 30))
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 2, 0, 1, 1)
        self.matchAttendanceEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.matchAttendanceEdit.setMinimumSize(QtCore.QSize(120, 30))
        self.matchAttendanceEdit.setMaximumSize(QtCore.QSize(120, 30))
        self.matchAttendanceEdit.setText("")
        self.matchAttendanceEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matchAttendanceEdit.setObjectName("matchAttendanceEdit")
        self.gridLayout_5.addWidget(self.matchAttendanceEdit, 2, 1, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(MatchEntryDlg)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 50, 871, 51))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        self.label_4.setMinimumSize(QtCore.QSize(45, 30))
        self.label_4.setMaximumSize(QtCore.QSize(45, 30))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.matchDateEdit = QtGui.QDateEdit(self.layoutWidget3)
        self.matchDateEdit.setMinimumSize(QtCore.QSize(120, 30))
        self.matchDateEdit.setMaximumSize(QtCore.QSize(120, 30))
        self.matchDateEdit.setMinimumDate(QtCore.QDate(1856, 1, 1))
        self.matchDateEdit.setCalendarPopup(True)
        self.matchDateEdit.setDate(QtCore.QDate(1901, 1, 1))
        self.matchDateEdit.setObjectName("matchDateEdit")
        self.horizontalLayout.addWidget(self.matchDateEdit)
        self.label_13 = QtGui.QLabel(self.layoutWidget3)
        self.label_13.setMinimumSize(QtCore.QSize(105, 30))
        self.label_13.setMaximumSize(QtCore.QSize(105, 30))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.matchCompSelect = QtGui.QComboBox(self.layoutWidget3)
        self.matchCompSelect.setMinimumSize(QtCore.QSize(330, 30))
        self.matchCompSelect.setMaximumSize(QtCore.QSize(330, 30))
        self.matchCompSelect.setObjectName("matchCompSelect")
        self.horizontalLayout.addWidget(self.matchCompSelect)
        self.label_14 = QtGui.QLabel(self.layoutWidget3)
        self.label_14.setMinimumSize(QtCore.QSize(50, 30))
        self.label_14.setMaximumSize(QtCore.QSize(50, 30))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.matchPhaseSelect = QtGui.QComboBox(self.layoutWidget3)
        self.matchPhaseSelect.setMinimumSize(QtCore.QSize(180, 30))
        self.matchPhaseSelect.setMaximumSize(QtCore.QSize(180, 30))
        self.matchPhaseSelect.setObjectName("matchPhaseSelect")
        self.horizontalLayout.addWidget(self.matchPhaseSelect)
        self.label.setBuddy(self.matchID_display)
        self.label_11.setBuddy(self.firstHalfLengthEdit)
        self.label_12.setBuddy(self.secondHalfLengthEdit)
        self.label_15.setBuddy(self.firstHalfLengthEdit)
        self.label_16.setBuddy(self.secondHalfLengthEdit)
        self.label_8.setBuddy(self.homemgrSelect)
        self.label_7.setBuddy(self.hometeamSelect)
        self.label_9.setBuddy(self.awayteamSelect)
        self.label_10.setBuddy(self.awaymgrSelect)
        self.label_5.setBuddy(self.matchVenueSelect)
        self.label_6.setBuddy(self.matchRefSelect)
        self.label_22.setBuddy(self.matchRefSelect)

        self.retranslateUi(MatchEntryDlg)
        QtCore.QMetaObject.connectSlotsByName(MatchEntryDlg)

    def retranslateUi(self, MatchEntryDlg):
        MatchEntryDlg.setWindowTitle(QtGui.QApplication.translate("MatchEntryDlg", "Match Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-weight:600;\">Match &amp;ID</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.firstEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "First Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.prevEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Previous Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.nextEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Next Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.lastEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Last Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.addEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Add Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.addEntry.setText(QtGui.QApplication.translate("MatchEntryDlg", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Delete Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEntry.setText(QtGui.QApplication.translate("MatchEntryDlg", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.saveEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Delete Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.saveEntry.setText(QtGui.QApplication.translate("MatchEntryDlg", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Close Window", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("MatchEntryDlg", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.leagueBox.setTitle(QtGui.QApplication.translate("MatchEntryDlg", "League Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Round</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lgRoundSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "League Round", None, QtGui.QApplication.UnicodeUTF8))
        self.knockoutBox.setTitle(QtGui.QApplication.translate("MatchEntryDlg", "Knockout Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Round</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.koRoundSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Knockout Round", None, QtGui.QApplication.UnicodeUTF8))
        self.koMatchdaySelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Knockout Round Matchday", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Matchday</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MatchEntryDlg", "Group Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Round</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.grpRoundSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Group Phase Round", None, QtGui.QApplication.UnicodeUTF8))
        self.groupSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Group Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Group</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.grpMatchdaySelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Group Round Matchday", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Matchday</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchtimeBox.setTitle(QtGui.QApplication.translate("MatchEntryDlg", "Match Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">1st half</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.firstHalfLengthEdit.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Total playing time of first half", None, QtGui.QApplication.UnicodeUTF8))
        self.firstHalfLengthEdit.setInputMask(QtGui.QApplication.translate("MatchEntryDlg", "99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.firstHalfLengthEdit.setText(QtGui.QApplication.translate("MatchEntryDlg", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">2nd half</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.secondHalfLengthEdit.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Total playing time of second half", None, QtGui.QApplication.UnicodeUTF8))
        self.secondHalfLengthEdit.setInputMask(QtGui.QApplication.translate("MatchEntryDlg", "99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.secondHalfLengthEdit.setText(QtGui.QApplication.translate("MatchEntryDlg", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">1st ET</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.firstExtraLengthEdit.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Total playing time of first extra time period", None, QtGui.QApplication.UnicodeUTF8))
        self.firstExtraLengthEdit.setInputMask(QtGui.QApplication.translate("MatchEntryDlg", "99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.firstExtraLengthEdit.setText(QtGui.QApplication.translate("MatchEntryDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">2nd ET</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.secondExtraLengthEdit.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Total playing time of second extra time period", None, QtGui.QApplication.UnicodeUTF8))
        self.secondExtraLengthEdit.setInputMask(QtGui.QApplication.translate("MatchEntryDlg", "99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.secondExtraLengthEdit.setText(QtGui.QApplication.translate("MatchEntryDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.hometeamBox.setTitle(QtGui.QApplication.translate("MatchEntryDlg", "Home Team", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Manager</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.homemgrSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Home team manager", None, QtGui.QApplication.UnicodeUTF8))
        self.hometeamSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Home team name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Team</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.homeLineupButton.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Home team match lineups", None, QtGui.QApplication.UnicodeUTF8))
        self.homeLineupButton.setText(QtGui.QApplication.translate("MatchEntryDlg", "&Home Lineup", None, QtGui.QApplication.UnicodeUTF8))
        self.awayteamBox.setTitle(QtGui.QApplication.translate("MatchEntryDlg", "Away Team", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Team</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.awayteamSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Away team name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Manager</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.awaymgrSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Away team manager", None, QtGui.QApplication.UnicodeUTF8))
        self.awayLineupButton.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Away team match lineups", None, QtGui.QApplication.UnicodeUTF8))
        self.awayLineupButton.setText(QtGui.QApplication.translate("MatchEntryDlg", "A&way Lineup", None, QtGui.QApplication.UnicodeUTF8))
        self.enviroButton.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Environmental conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.enviroButton.setText(QtGui.QApplication.translate("MatchEntryDlg", "&Environments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Venue</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchVenueSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Match Venue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Referee</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchRefSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Match Referee", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Attendance</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchAttendanceEdit.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Match Attendance", None, QtGui.QApplication.UnicodeUTF8))
        self.matchAttendanceEdit.setInputMask(QtGui.QApplication.translate("MatchEntryDlg", "999999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Date</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchDateEdit.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Match date", None, QtGui.QApplication.UnicodeUTF8))
        self.matchDateEdit.setDisplayFormat(QtGui.QApplication.translate("MatchEntryDlg", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\"> Competition</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchCompSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Competition Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\"> Phase</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchPhaseSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Competition Phase", None, QtGui.QApplication.UnicodeUTF8))

import fmrd_resources_rc
