# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/match_entry.ui'
#
# Created: Sat Aug  6 01:32:13 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MatchEntryDlg(object):
    def setupUi(self, MatchEntryDlg):
        MatchEntryDlg.setObjectName("MatchEntryDlg")
        MatchEntryDlg.resize(848, 424)
        MatchEntryDlg.setMinimumSize(QtCore.QSize(848, 424))
        MatchEntryDlg.setMaximumSize(QtCore.QSize(848, 424))
        self.label_4 = QtGui.QLabel(MatchEntryDlg)
        self.label_4.setGeometry(QtCore.QRect(208, 9, 36, 17))
        self.label_4.setObjectName("label_4")
        self.matchDateEdit = QtGui.QLineEdit(MatchEntryDlg)
        self.matchDateEdit.setGeometry(QtCore.QRect(250, 9, 91, 27))
        self.matchDateEdit.setMinimumSize(QtCore.QSize(91, 27))
        self.matchDateEdit.setMaximumSize(QtCore.QSize(91, 27))
        self.matchDateEdit.setObjectName("matchDateEdit")
        self.line = QtGui.QFrame(MatchEntryDlg)
        self.line.setGeometry(QtCore.QRect(9, 42, 831, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(MatchEntryDlg)
        self.line_2.setGeometry(QtCore.QRect(410, 60, 16, 281))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.overviewBox = QtGui.QGroupBox(MatchEntryDlg)
        self.overviewBox.setGeometry(QtCore.QRect(10, 60, 391, 214))
        self.overviewBox.setObjectName("overviewBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.overviewBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtGui.QLabel(self.overviewBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.matchCompSelect = QtGui.QComboBox(self.overviewBox)
        self.matchCompSelect.setMinimumSize(QtCore.QSize(271, 31))
        self.matchCompSelect.setMaximumSize(QtCore.QSize(271, 31))
        self.matchCompSelect.setObjectName("matchCompSelect")
        self.gridLayout_3.addWidget(self.matchCompSelect, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.overviewBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.matchRoundSelect = QtGui.QComboBox(self.overviewBox)
        self.matchRoundSelect.setMinimumSize(QtCore.QSize(271, 31))
        self.matchRoundSelect.setMaximumSize(QtCore.QSize(271, 31))
        self.matchRoundSelect.setObjectName("matchRoundSelect")
        self.gridLayout_3.addWidget(self.matchRoundSelect, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 24, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.overviewBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.matchVenueSelect = QtGui.QComboBox(self.overviewBox)
        self.matchVenueSelect.setMinimumSize(QtCore.QSize(271, 31))
        self.matchVenueSelect.setMaximumSize(QtCore.QSize(271, 31))
        self.matchVenueSelect.setObjectName("matchVenueSelect")
        self.gridLayout_3.addWidget(self.matchVenueSelect, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.overviewBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.matchRefSelect = QtGui.QComboBox(self.overviewBox)
        self.matchRefSelect.setMinimumSize(QtCore.QSize(271, 31))
        self.matchRefSelect.setMaximumSize(QtCore.QSize(271, 31))
        self.matchRefSelect.setObjectName("matchRefSelect")
        self.gridLayout_3.addWidget(self.matchRefSelect, 4, 1, 1, 1)
        self.line_3 = QtGui.QFrame(MatchEntryDlg)
        self.line_3.setGeometry(QtCore.QRect(0, 350, 841, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.matchID_display = QtGui.QLineEdit(MatchEntryDlg)
        self.matchID_display.setGeometry(QtCore.QRect(82, 9, 120, 27))
        self.matchID_display.setMaximumSize(QtCore.QSize(120, 27))
        self.matchID_display.setStyleSheet("background-color: rgb(194, 190, 186);")
        self.matchID_display.setMaxLength(7)
        self.matchID_display.setReadOnly(True)
        self.matchID_display.setObjectName("matchID_display")
        self.label = QtGui.QLabel(MatchEntryDlg)
        self.label.setGeometry(QtCore.QRect(9, 9, 67, 17))
        self.label.setObjectName("label")
        self.layoutWidget = QtGui.QWidget(MatchEntryDlg)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 280, 332, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.timeBox = QtGui.QGroupBox(self.layoutWidget)
        self.timeBox.setMinimumSize(QtCore.QSize(267, 63))
        self.timeBox.setObjectName("timeBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.timeBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtGui.QLabel(self.timeBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.firstHalfLengthEdit = QtGui.QLineEdit(self.timeBox)
        self.firstHalfLengthEdit.setMinimumSize(QtCore.QSize(51, 27))
        self.firstHalfLengthEdit.setMaximumSize(QtCore.QSize(51, 27))
        self.firstHalfLengthEdit.setMaxLength(2)
        self.firstHalfLengthEdit.setObjectName("firstHalfLengthEdit")
        self.horizontalLayout.addWidget(self.firstHalfLengthEdit)
        self.label_12 = QtGui.QLabel(self.timeBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.secondHalfLengthEdit = QtGui.QLineEdit(self.timeBox)
        self.secondHalfLengthEdit.setMinimumSize(QtCore.QSize(51, 27))
        self.secondHalfLengthEdit.setMaximumSize(QtCore.QSize(51, 27))
        self.secondHalfLengthEdit.setMaxLength(2)
        self.secondHalfLengthEdit.setObjectName("secondHalfLengthEdit")
        self.horizontalLayout.addWidget(self.secondHalfLengthEdit)
        self.horizontalLayout_5.addWidget(self.timeBox)
        spacerItem1 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.layoutWidget1 = QtGui.QWidget(MatchEntryDlg)
        self.layoutWidget1.setGeometry(QtCore.QRect(420, 360, 391, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addEntry = QtGui.QPushButton(self.layoutWidget1)
        self.addEntry.setMinimumSize(QtCore.QSize(85, 27))
        self.addEntry.setMaximumSize(QtCore.QSize(85, 27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addEntry.setIcon(icon)
        self.addEntry.setObjectName("addEntry")
        self.horizontalLayout_3.addWidget(self.addEntry)
        self.deleteEntry = QtGui.QPushButton(self.layoutWidget1)
        self.deleteEntry.setMinimumSize(QtCore.QSize(85, 27))
        self.deleteEntry.setMaximumSize(QtCore.QSize(85, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteEntry.setIcon(icon1)
        self.deleteEntry.setObjectName("deleteEntry")
        self.horizontalLayout_3.addWidget(self.deleteEntry)
        self.closeButton = QtGui.QPushButton(self.layoutWidget1)
        self.closeButton.setMinimumSize(QtCore.QSize(85, 27))
        self.closeButton.setMaximumSize(QtCore.QSize(85, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon2)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.layoutWidget2 = QtGui.QWidget(MatchEntryDlg)
        self.layoutWidget2.setGeometry(QtCore.QRect(42, 360, 328, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.firstEntry = QtGui.QPushButton(self.layoutWidget2)
        self.firstEntry.setMinimumSize(QtCore.QSize(77, 27))
        self.firstEntry.setMaximumSize(QtCore.QSize(77, 27))
        self.firstEntry.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.firstEntry.setIcon(icon3)
        self.firstEntry.setObjectName("firstEntry")
        self.horizontalLayout_2.addWidget(self.firstEntry)
        self.prevEntry = QtGui.QPushButton(self.layoutWidget2)
        self.prevEntry.setMinimumSize(QtCore.QSize(77, 27))
        self.prevEntry.setMaximumSize(QtCore.QSize(77, 27))
        self.prevEntry.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevEntry.setIcon(icon4)
        self.prevEntry.setObjectName("prevEntry")
        self.horizontalLayout_2.addWidget(self.prevEntry)
        self.nextEntry = QtGui.QPushButton(self.layoutWidget2)
        self.nextEntry.setMinimumSize(QtCore.QSize(77, 27))
        self.nextEntry.setMaximumSize(QtCore.QSize(77, 27))
        self.nextEntry.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextEntry.setIcon(icon5)
        self.nextEntry.setObjectName("nextEntry")
        self.horizontalLayout_2.addWidget(self.nextEntry)
        self.lastEntry = QtGui.QPushButton(self.layoutWidget2)
        self.lastEntry.setMinimumSize(QtCore.QSize(77, 27))
        self.lastEntry.setMaximumSize(QtCore.QSize(77, 27))
        self.lastEntry.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lastEntry.setIcon(icon6)
        self.lastEntry.setObjectName("lastEntry")
        self.horizontalLayout_2.addWidget(self.lastEntry)
        self.layoutWidget3 = QtGui.QWidget(MatchEntryDlg)
        self.layoutWidget3.setGeometry(QtCore.QRect(431, 61, 381, 216))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hometeamBox = QtGui.QGroupBox(self.layoutWidget3)
        self.hometeamBox.setObjectName("hometeamBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.hometeamBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtGui.QLabel(self.hometeamBox)
        self.label_8.setMinimumSize(QtCore.QSize(86, 31))
        self.label_8.setMaximumSize(QtCore.QSize(86, 31))
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.homemgrSelect = QtGui.QComboBox(self.hometeamBox)
        self.homemgrSelect.setEnabled(True)
        self.homemgrSelect.setMinimumSize(QtCore.QSize(221, 31))
        self.homemgrSelect.setMaximumSize(QtCore.QSize(221, 31))
        self.homemgrSelect.setObjectName("homemgrSelect")
        self.gridLayout_2.addWidget(self.homemgrSelect, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.hometeamBox)
        self.label_7.setMinimumSize(QtCore.QSize(86, 31))
        self.label_7.setMaximumSize(QtCore.QSize(86, 31))
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.hometeamSelect = QtGui.QComboBox(self.hometeamBox)
        self.hometeamSelect.setMinimumSize(QtCore.QSize(221, 31))
        self.hometeamSelect.setMaximumSize(QtCore.QSize(221, 31))
        self.hometeamSelect.setObjectName("hometeamSelect")
        self.gridLayout_2.addWidget(self.hometeamSelect, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.hometeamBox)
        self.awayteamBox = QtGui.QGroupBox(self.layoutWidget3)
        self.awayteamBox.setObjectName("awayteamBox")
        self.gridLayout = QtGui.QGridLayout(self.awayteamBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtGui.QLabel(self.awayteamBox)
        self.label_9.setMinimumSize(QtCore.QSize(86, 31))
        self.label_9.setMaximumSize(QtCore.QSize(86, 31))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.awayteamSelect = QtGui.QComboBox(self.awayteamBox)
        self.awayteamSelect.setEnabled(True)
        self.awayteamSelect.setMinimumSize(QtCore.QSize(221, 31))
        self.awayteamSelect.setMaximumSize(QtCore.QSize(221, 31))
        self.awayteamSelect.setObjectName("awayteamSelect")
        self.gridLayout.addWidget(self.awayteamSelect, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.awayteamBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.awaymgrSelect = QtGui.QComboBox(self.awayteamBox)
        self.awaymgrSelect.setEnabled(True)
        self.awaymgrSelect.setMinimumSize(QtCore.QSize(221, 31))
        self.awaymgrSelect.setMaximumSize(QtCore.QSize(221, 31))
        self.awaymgrSelect.setObjectName("awaymgrSelect")
        self.gridLayout.addWidget(self.awaymgrSelect, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.awayteamBox)
        self.layoutWidget4 = QtGui.QWidget(MatchEntryDlg)
        self.layoutWidget4.setGeometry(QtCore.QRect(430, 278, 381, 61))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.homeLineupButton = QtGui.QPushButton(self.layoutWidget4)
        self.homeLineupButton.setEnabled(True)
        self.homeLineupButton.setMinimumSize(QtCore.QSize(109, 27))
        self.homeLineupButton.setMaximumSize(QtCore.QSize(109, 27))
        self.homeLineupButton.setObjectName("homeLineupButton")
        self.horizontalLayout_4.addWidget(self.homeLineupButton)
        spacerItem4 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.awayLineupButton = QtGui.QPushButton(self.layoutWidget4)
        self.awayLineupButton.setEnabled(True)
        self.awayLineupButton.setMinimumSize(QtCore.QSize(109, 27))
        self.awayLineupButton.setMaximumSize(QtCore.QSize(109, 27))
        self.awayLineupButton.setObjectName("awayLineupButton")
        self.horizontalLayout_4.addWidget(self.awayLineupButton)
        spacerItem5 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.enviroButton = QtGui.QPushButton(self.layoutWidget4)
        self.enviroButton.setMinimumSize(QtCore.QSize(109, 27))
        self.enviroButton.setMaximumSize(QtCore.QSize(109, 27))
        self.enviroButton.setDefault(False)
        self.enviroButton.setObjectName("enviroButton")
        self.horizontalLayout_4.addWidget(self.enviroButton)
        self.label_4.setBuddy(self.matchDateEdit)
        self.label_2.setBuddy(self.matchCompSelect)
        self.label_3.setBuddy(self.matchRoundSelect)
        self.label_5.setBuddy(self.matchVenueSelect)
        self.label_6.setBuddy(self.matchRefSelect)
        self.label.setBuddy(self.matchID_display)
        self.label_11.setBuddy(self.firstHalfLengthEdit)
        self.label_12.setBuddy(self.secondHalfLengthEdit)
        self.label_8.setBuddy(self.homemgrSelect)
        self.label_7.setBuddy(self.hometeamSelect)
        self.label_9.setBuddy(self.awayteamSelect)
        self.label_10.setBuddy(self.awaymgrSelect)

        self.retranslateUi(MatchEntryDlg)
        QtCore.QMetaObject.connectSlotsByName(MatchEntryDlg)

    def retranslateUi(self, MatchEntryDlg):
        MatchEntryDlg.setWindowTitle(QtGui.QApplication.translate("MatchEntryDlg", "Match Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Date</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchDateEdit.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Match date (YYYY-MM-DD)", None, QtGui.QApplication.UnicodeUTF8))
        self.matchDateEdit.setInputMask(QtGui.QApplication.translate("MatchEntryDlg", "9999-99-99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.matchDateEdit.setText(QtGui.QApplication.translate("MatchEntryDlg", "1901-01-01", None, QtGui.QApplication.UnicodeUTF8))
        self.overviewBox.setTitle(QtGui.QApplication.translate("MatchEntryDlg", "Match Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Competition</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchCompSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Football competition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Round</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchRoundSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Competition phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Venue</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchVenueSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Match venue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Referee</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matchRefSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Match referee", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-weight:600;\">Match &amp;ID</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.timeBox.setTitle(QtGui.QApplication.translate("MatchEntryDlg", "Match Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">1st half</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.firstHalfLengthEdit.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Total playing time of first half", None, QtGui.QApplication.UnicodeUTF8))
        self.firstHalfLengthEdit.setInputMask(QtGui.QApplication.translate("MatchEntryDlg", "99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.firstHalfLengthEdit.setText(QtGui.QApplication.translate("MatchEntryDlg", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">2nd half</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.secondHalfLengthEdit.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Total playing time of second half", None, QtGui.QApplication.UnicodeUTF8))
        self.secondHalfLengthEdit.setInputMask(QtGui.QApplication.translate("MatchEntryDlg", "99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.secondHalfLengthEdit.setText(QtGui.QApplication.translate("MatchEntryDlg", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.addEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Add Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.addEntry.setText(QtGui.QApplication.translate("MatchEntryDlg", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Delete Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEntry.setText(QtGui.QApplication.translate("MatchEntryDlg", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Close Window", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("MatchEntryDlg", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.firstEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "First Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.prevEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Previous Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.nextEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Next Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.lastEntry.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Last Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.hometeamBox.setTitle(QtGui.QApplication.translate("MatchEntryDlg", "Home Team", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Manager</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.homemgrSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Home team manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Team</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.hometeamSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Home team name", None, QtGui.QApplication.UnicodeUTF8))
        self.awayteamBox.setTitle(QtGui.QApplication.translate("MatchEntryDlg", "Away Team", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Team</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.awayteamSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Away team name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MatchEntryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Manager</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.awaymgrSelect.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Away team manager", None, QtGui.QApplication.UnicodeUTF8))
        self.homeLineupButton.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Home team match lineups", None, QtGui.QApplication.UnicodeUTF8))
        self.homeLineupButton.setText(QtGui.QApplication.translate("MatchEntryDlg", "&Home Lineup", None, QtGui.QApplication.UnicodeUTF8))
        self.awayLineupButton.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Away team match lineups", None, QtGui.QApplication.UnicodeUTF8))
        self.awayLineupButton.setText(QtGui.QApplication.translate("MatchEntryDlg", "A&way Lineup", None, QtGui.QApplication.UnicodeUTF8))
        self.enviroButton.setToolTip(QtGui.QApplication.translate("MatchEntryDlg", "Environmental conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.enviroButton.setText(QtGui.QApplication.translate("MatchEntryDlg", "&Environments", None, QtGui.QApplication.UnicodeUTF8))

import fmrd_resources_rc
