# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/venuehistory_entry.ui'
#
# Created: Thu Dec 29 23:31:14 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_VenueHistoryDlg(object):
    def setupUi(self, VenueHistoryDlg):
        VenueHistoryDlg.setObjectName("VenueHistoryDlg")
        VenueHistoryDlg.resize(800, 300)
        VenueHistoryDlg.setMinimumSize(QtCore.QSize(800, 300))
        VenueHistoryDlg.setMaximumSize(QtCore.QSize(800, 300))
        self.frame = QtGui.QFrame(VenueHistoryDlg)
        self.frame.setGeometry(QtCore.QRect(690, 50, 101, 171))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.closeButton = QtGui.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(10, 130, 80, 33))
        self.closeButton.setMinimumSize(QtCore.QSize(80, 33))
        self.closeButton.setMaximumSize(QtCore.QSize(80, 33))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon)
        self.closeButton.setObjectName("closeButton")
        self.saveEntry = QtGui.QPushButton(self.frame)
        self.saveEntry.setGeometry(QtCore.QRect(10, 50, 80, 33))
        self.saveEntry.setMinimumSize(QtCore.QSize(80, 33))
        self.saveEntry.setMaximumSize(QtCore.QSize(80, 33))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveEntry.setIcon(icon1)
        self.saveEntry.setObjectName("saveEntry")
        self.deleteEntry = QtGui.QPushButton(self.frame)
        self.deleteEntry.setGeometry(QtCore.QRect(10, 90, 80, 33))
        self.deleteEntry.setMinimumSize(QtCore.QSize(80, 33))
        self.deleteEntry.setMaximumSize(QtCore.QSize(80, 33))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteEntry.setIcon(icon2)
        self.deleteEntry.setObjectName("deleteEntry")
        self.addEntry = QtGui.QPushButton(self.frame)
        self.addEntry.setGeometry(QtCore.QRect(10, 10, 80, 33))
        self.addEntry.setMinimumSize(QtCore.QSize(80, 33))
        self.addEntry.setMaximumSize(QtCore.QSize(80, 33))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addEntry.setIcon(icon3)
        self.addEntry.setObjectName("addEntry")
        self.frame_2 = QtGui.QFrame(VenueHistoryDlg)
        self.frame_2.setGeometry(QtCore.QRect(200, 240, 331, 51))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.firstEntry = QtGui.QPushButton(self.frame_2)
        self.firstEntry.setGeometry(QtCore.QRect(10, 10, 71, 33))
        self.firstEntry.setMinimumSize(QtCore.QSize(71, 33))
        self.firstEntry.setMaximumSize(QtCore.QSize(71, 33))
        self.firstEntry.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.firstEntry.setIcon(icon4)
        self.firstEntry.setIconSize(QtCore.QSize(16, 16))
        self.firstEntry.setObjectName("firstEntry")
        self.prevEntry = QtGui.QPushButton(self.frame_2)
        self.prevEntry.setGeometry(QtCore.QRect(90, 10, 71, 33))
        self.prevEntry.setMinimumSize(QtCore.QSize(71, 33))
        self.prevEntry.setMaximumSize(QtCore.QSize(71, 33))
        self.prevEntry.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevEntry.setIcon(icon5)
        self.prevEntry.setObjectName("prevEntry")
        self.nextEntry = QtGui.QPushButton(self.frame_2)
        self.nextEntry.setGeometry(QtCore.QRect(170, 10, 71, 33))
        self.nextEntry.setMinimumSize(QtCore.QSize(71, 33))
        self.nextEntry.setMaximumSize(QtCore.QSize(71, 33))
        self.nextEntry.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextEntry.setIcon(icon6)
        self.nextEntry.setObjectName("nextEntry")
        self.lastEntry = QtGui.QPushButton(self.frame_2)
        self.lastEntry.setGeometry(QtCore.QRect(250, 10, 71, 33))
        self.lastEntry.setMinimumSize(QtCore.QSize(71, 33))
        self.lastEntry.setMaximumSize(QtCore.QSize(71, 33))
        self.lastEntry.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lastEntry.setIcon(icon7)
        self.lastEntry.setObjectName("lastEntry")
        self.layoutWidget = QtGui.QWidget(VenueHistoryDlg)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 650, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(150, 30))
        self.label_2.setMaximumSize(QtCore.QSize(150, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.venueDateEdit = QtGui.QDateEdit(self.layoutWidget)
        self.venueDateEdit.setMinimumSize(QtCore.QSize(120, 30))
        self.venueDateEdit.setMaximumSize(QtCore.QSize(120, 30))
        self.venueDateEdit.setMaximumDate(QtCore.QDate(7999, 12, 31))
        self.venueDateEdit.setCalendarPopup(True)
        self.venueDateEdit.setObjectName("venueDateEdit")
        self.gridLayout.addWidget(self.venueDateEdit, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(150, 30))
        self.label_8.setMaximumSize(QtCore.QSize(150, 30))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.venueSurfaceSelect = QtGui.QComboBox(self.layoutWidget)
        self.venueSurfaceSelect.setMinimumSize(QtCore.QSize(180, 30))
        self.venueSurfaceSelect.setMaximumSize(QtCore.QSize(180, 30))
        self.venueSurfaceSelect.setObjectName("venueSurfaceSelect")
        self.gridLayout.addWidget(self.venueSurfaceSelect, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(150, 30))
        self.label_3.setMaximumSize(QtCore.QSize(150, 30))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.venueLengthEdit = QtGui.QLineEdit(self.layoutWidget)
        self.venueLengthEdit.setMinimumSize(QtCore.QSize(120, 30))
        self.venueLengthEdit.setMaximumSize(QtCore.QSize(120, 30))
        self.venueLengthEdit.setObjectName("venueLengthEdit")
        self.gridLayout.addWidget(self.venueLengthEdit, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(150, 30))
        self.label_4.setMaximumSize(QtCore.QSize(150, 30))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.venueWidthEdit = QtGui.QLineEdit(self.layoutWidget)
        self.venueWidthEdit.setMinimumSize(QtCore.QSize(120, 30))
        self.venueWidthEdit.setMaximumSize(QtCore.QSize(120, 30))
        self.venueWidthEdit.setObjectName("venueWidthEdit")
        self.horizontalLayout.addWidget(self.venueWidthEdit)
        spacerItem = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(150, 30))
        self.label_7.setMaximumSize(QtCore.QSize(150, 30))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.venueCapacityEdit = QtGui.QLineEdit(self.layoutWidget)
        self.venueCapacityEdit.setMinimumSize(QtCore.QSize(120, 30))
        self.venueCapacityEdit.setMaximumSize(QtCore.QSize(120, 30))
        self.venueCapacityEdit.setObjectName("venueCapacityEdit")
        self.gridLayout.addWidget(self.venueCapacityEdit, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(150, 30))
        self.label_6.setMaximumSize(QtCore.QSize(150, 30))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.venueSeatsEdit = QtGui.QLineEdit(self.layoutWidget)
        self.venueSeatsEdit.setMinimumSize(QtCore.QSize(120, 30))
        self.venueSeatsEdit.setMaximumSize(QtCore.QSize(120, 30))
        self.venueSeatsEdit.setObjectName("venueSeatsEdit")
        self.horizontalLayout_2.addWidget(self.venueSeatsEdit)
        spacerItem1 = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 3, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(VenueHistoryDlg)
        self.layoutWidget1.setGeometry(QtCore.QRect(22, 10, 651, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(60, 20))
        self.label.setMaximumSize(QtCore.QSize(60, 20))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.venueName_display = QtGui.QLineEdit(self.layoutWidget1)
        self.venueName_display.setMinimumSize(QtCore.QSize(300, 30))
        self.venueName_display.setMaximumSize(QtCore.QSize(300, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(194, 190, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 190, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 190, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 190, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 190, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 190, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 190, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 190, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 190, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.venueName_display.setPalette(palette)
        self.venueName_display.setReadOnly(True)
        self.venueName_display.setObjectName("venueName_display")
        self.horizontalLayout_3.addWidget(self.venueName_display)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(30, 30))
        self.label_5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.historyID_display = QtGui.QLineEdit(self.layoutWidget1)
        self.historyID_display.setMinimumSize(QtCore.QSize(120, 30))
        self.historyID_display.setMaximumSize(QtCore.QSize(120, 30))
        self.historyID_display.setStyleSheet("background-color: rgb(194, 190, 186);")
        self.historyID_display.setReadOnly(True)
        self.historyID_display.setObjectName("historyID_display")
        self.horizontalLayout_3.addWidget(self.historyID_display)
        spacerItem2 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)

        self.retranslateUi(VenueHistoryDlg)
        QtCore.QMetaObject.connectSlotsByName(VenueHistoryDlg)

    def retranslateUi(self, VenueHistoryDlg):
        VenueHistoryDlg.setWindowTitle(QtGui.QApplication.translate("VenueHistoryDlg", "Surface/Capacity History", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Close Window", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("VenueHistoryDlg", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.saveEntry.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Save Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.saveEntry.setText(QtGui.QApplication.translate("VenueHistoryDlg", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEntry.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Delete Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEntry.setText(QtGui.QApplication.translate("VenueHistoryDlg", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.addEntry.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Add Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.addEntry.setText(QtGui.QApplication.translate("VenueHistoryDlg", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.firstEntry.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "First Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.prevEntry.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Previous Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.nextEntry.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Next Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.lastEntry.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Last Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("VenueHistoryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Effective Date</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.venueDateEdit.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Effective date of stadium data (YYYY-MM-DD)", None, QtGui.QApplication.UnicodeUTF8))
        self.venueDateEdit.setDisplayFormat(QtGui.QApplication.translate("VenueHistoryDlg", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("VenueHistoryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Playing Surface</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.venueSurfaceSelect.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Type of field surface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("VenueHistoryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Field Length (m)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.venueLengthEdit.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Field length (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("VenueHistoryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Field Width (m)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.venueWidthEdit.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Field width (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("VenueHistoryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Capacity</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.venueCapacityEdit.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Total venue capacity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("VenueHistoryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Seats</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.venueSeatsEdit.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Total number of seats in venue", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("VenueHistoryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Venue</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.venueName_display.setToolTip(QtGui.QApplication.translate("VenueHistoryDlg", "Venue name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("VenueHistoryDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">ID</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import fmrd_resources_rc
